name: Coverage CI

on:
  push:
    branches:
      - master
      - feat/addDeployCovWorkflow
  workflow_dispatch:

jobs:
  coverage-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Initialize
        uses: ./.github/actions/initialize

      - name: Run test
        run: |
          pytest --cov=src --cov-report=html
          rm htmlcov/.gitignore

      - name: Coverage Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./htmlcov
